### ISSUE TITLE
Probleme inventar Tablet Kleidungsmenü

### ISSUE THREAD

**Issue by BlackBeast79** [Beyond-RP/BeyondRoleplay-Public#1]
**Beschreibe den Fehler**
hallo zusammen war ja jetzt einige zeit nicht IG und habe daher heute mal wieder geschaut ob ich ausgeschlafen habe.
nun taten sich bei mir einige probleme auf.
ich geh davon aus das es sich da um irgendwelche anzeige fehler handelt 

**Reproduzieren**
nach Jedem Login selbes problem (kleidungsmenü legt sich nach einiger zeit anscheinend)

**Erwartetes Verhalten**
An sich problemlose hanhabung der Menüs und des inventars

**Screenshots**
Fügen Sie gegebenenfalls Screenshots hinzu, um Ihr Problem zu erklären.
![Inventar](https://user-images.githubusercontent.com/23469608/145727135-21754c7a-b5f4-44b3-af21-73d354173188.JPG)
![Tablet](https://user-images.githubusercontent.com/23469608/145727140-e42c6be7-d051-4b98-ba5c-db89bea493b9.JPG)

**Desktop (bitte füllen Sie die folgenden Informationen aus):**
  - Betriebssystem: Win10
  - Prozessor : AMD Ryzen 5 2600 Six-Core Processor
  - GrafikKarte : Radeon RX 570 Series
  - Arbeitsspeicher : 32GB DDR4-2666

**Zusätzlicher Kontext**
Anbei CEFlog Launcher Log und Client Log
in der CEF ka was das für ein Error ist. Alt V wiki fand ich keinen eintrag dazu

[cef.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7699428/cef.log)
[client_12-12-2021_19-42-10.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7699429/client_12-12-2021_19-42-10.log)
[launcher.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7699430/launcher.log)

**Comment by BlackBeast79** [comment]
so nach Reinstall GTA V und Alt V was für mich jetzt hardcore lösung war , da auch reperatur von Steam also lokale Daten auf Fehler überprüfen keine besserung brachte hat sich das problem leider nicht beheben lassen.

Anbei nochmals das Problem welches ich schon im Discord angeschrieben habe mit Login unten rechts schreiben muss ich aber in der mitte da wo das layout ja eigentlich sein sollte. 
Zuerst Serverauswahl
![Server auswahl](https://user-images.githubusercontent.com/23469608/145829527-1ade247d-89a2-4837-939d-610dadc686b3.JPG)
Hier dann wie es aktuell bei mir aussieht mit dem Login
![Login](https://user-images.githubusercontent.com/23469608/145829542-14b67216-bc6a-411f-955d-b23db8779aa3.JPG)

**Comment by Asrothear** [comment]
Ich bräuchte noch folgende Infos:
  - Desktopauflösung [z.b. 2560x1440]
  - Desktopskalierung [z.b. 125%]
  - GTA:V Auflösung [z.b. 1920x1080]

**Comment by BlackBeast79** [comment]
Desktopauflösung 1920X1080
    Desktopskalierung KA nie was geändert
    GTA:V Auflösung Fenstermodus 1914 X 1051
    auch Fenster modus ohne Rahmen 1980 X 1008
    als auch Vollbild 1920X1080
bei allen 3 Varianten selber effekt eine Ausnahme Tablett wird richtig angezeigt bei Fenstermodus ohne Rahmen inventar aber nicht

**Comment by Asrothear** [comment]
Die Desktopskalierung findest du unter:
Rechtsklick auf den Desktop -> Anzeigeeinstellungen

**Comment by BlackBeast79** [comment]
100% (empfohlen)

**Comment by Asrothear** [comment]
Es wäre mal gut wenn wir uns das im TS3 anschauen können

**Comment by Asrothear** [comment]
Problem AMD seitig behoben
