### ISSUE TITLE
BUGREPORT-Loginproblem

### ISSUE THREAD

**Issue by BlackBeast79** [Beyond-RP/BeyondRoleplay-Public#5]
**Beschreibe den Fehler**

Kann nicht Einloggen da Angeblich syncronisation mit dem Discord nicht stimmt

Error: #NS03D5DC
Eine Verküpfung mit Discord konnte in unserem Forum nicht gefunden werden!
Bitte vergewissere dich das du in unserem Forum den Discord-Sync korrekt eingerichtet hast.
Ist das erledigt, kannst du dich mit dem Server verbinden.

**Reproduzieren**

Nach erneuter Syncronisation selbes Fehlerbild wieder

**Erwartetes Verhalten**

Nach erneuter Syncronisation mit dem DC hätte ich erwartet das ich mich danach normal Einloggen kann
![LoginProblem](https://user-images.githubusercontent.com/23469608/147403151-0322403a-58dc-4139-8014-969c240ea0de.JPG)

**Screenshots**
Fügen Sie gegebenenfalls Screenshots hinzu, um Ihr Problem zu erklären.

**Desktop (bitte füllen Sie die folgenden Informationen aus):**
  - Betriebssystem: Win 10
  - Desktopauflösung 1920X1080
  - Desktopskalierung 100%
  - GTA:V Auflösung 1920x1080  
  - GTA:V Bildschirmmodus  Vollbild
  - GTA:V Version  Aktuelle Steam Version 1.0.231.0 
  - AltV Version alt:V Launcher - 8.6

**LogFiles**
Bitte folgende Logs aus dem AltV Verzeichnis anfügen.

[client_26-12-2021_09-30-41.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776735/client_26-12-2021_09-30-41.log)
[launcher.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776736/launcher.log)
[cef.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776737/cef.log)

**Zusätzlicher Kontext**
Fügen Sie hier jeden weiteren Kontext zu dem Problem hinzu.

**Comment by Asrothear** [comment]
Dazu bräuchte ich dann noch einmal den Forum User name und DC Namen

**Comment by Asrothear** [comment]
Sync wurde Bestätigt, es gab da eine Verzögerung im Forum
