### ISSUE TITLE
BUGREPORT-Garage Bahama Mamas

### ISSUE THREAD

**Issue by BlackBeast79** [Beyond-RP/BeyondRoleplay-Public#6]
**Beschreibe den Fehler**

Habe alle meine Fahrzeuge in der Garage Bahama Mamas.
Bisher hatte ich nie probleme meine fahrzeuge vom Garagenwärter aushändigen zu lassen, seit kurz vor dem update kann ich nicht mehr auf die Fahrzeuge zugreifen. mein ortungssystem sagt mir zwar Fahrzeug ist auf Parkplatz aber anscheinend benötige ich da eine Brille, da ich sie nicht seh. Bin auch schon mal um den Block gelaufen und hab ein powersleep eingelegt aber beides hat nicht geholfen

**Reproduzieren**
Schritte zum Reproduzieren des Verhaltens:
1. Gehe zu 'Garage Bahama Mamas'
2. Klicken Sie auf 'Scorcher, Dilettante, Sanchez, Pony oder Akuma '
4. Siehe Fehler kein Fahrzeug wird physisch ausgelagert im System stehen sie auf parkplatz auch wenn mit dem aktuell anscheinend im boden versunkenen parkwächter rede kann ich sie nach dem er sie mir bereitgestellt hat auch wieder einparken lassen

**Erwartetes Verhalten**
wenn ich den Parkwächter anspreche und mein Fahrzeug bereitstellen lasse würde ich erwarten das es in einer der 4 parkzonen steht

**Screenshots**
Fügen Sie gegebenenfalls Screenshots hinzu, um Ihr Problem zu erklären.
![01 Garage eingelagert](https://user-images.githubusercontent.com/23469608/147406197-a97e5668-9a87-40fe-af59-06a04abbb263.JPG)
![02 Garage Übersicht alle eingeparkt](https://user-images.githubusercontent.com/23469608/147406199-f96aafd2-83e0-462b-bed9-bac0f3a739bd.JPG)
![03 Garage Parkservice](https://user-images.githubusercontent.com/23469608/147406200-5090a69c-67a3-4fbd-8a95-fcd961433a65.JPG)
![04 Garage Übersicht Dilettante angefordert](https://user-images.githubusercontent.com/23469608/147406201-30f4258a-425e-4254-860d-ec96a0733f88.JPG)
![05 Garage ein Fahrzeug unterwegs_LI](https://user-images.githubusercontent.com/23469608/147406265-21924d3e-c6e6-4789-9521-2c0feb415733.jpg)
![06 Garage Stellplätze obwohl Fahrzeug ausgelagert](https://user-images.githubusercontent.com/23469608/147406267-db01444b-780e-41b6-af20-e5a0fa65d70e.JPG)
![07 Garage ein Fahrzeug Standort](https://user-images.githubusercontent.com/23469608/147406204-f0a9c749-e7af-4635-b309-95e7e4e9f073.JPG)
![08 Garage Stellplätze obwohl Fahrzeug ausgelagert nach Relog](https://user-images.githubusercontent.com/23469608/147406205-1d06779a-a862-4b05-a877-994798284518.JPG)

**Desktop (bitte füllen Sie die folgenden Informationen aus):**

   - Betriebssystem: Win 10
   - Desktopauflösung 1920X1080
   - Desktopskalierung 100%
   - GTA:V Auflösung 1920x1080
   - GTA:V Bildschirmmodus Vollbild
   - GTA:V Version Aktuelle Steam Version 1.0.231.0
   - AltV Version alt:V Launcher - 8.6

**LogFiles**
Bitte folgende Logs aus dem AltV Verzeichnis anfügen.
[cef.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776889/cef.log)
[client_26-12-2021_11-36-34.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776890/client_26-12-2021_11-36-34.log)
[client_26-12-2021_12-04-48.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776891/client_26-12-2021_12-04-48.log)
[launcher.log](https://github.com/Beyond-RP/BeyondRoleplay-Public/files/7776892/launcher.log)

**Zusätzlicher Kontext**
Fügen Sie hier jeden weiteren Kontext zu dem Problem hinzu.
client_26-12-2021_11-36-34.log vor Relog
client_26-12-2021_12-04-48.log nach Relog

**Comment by BeyondRoleplayDE** [comment]
Versuch mal bitte mit # den chat zu öffnen und gib /unstuck ein. Kann sein das du in der falschen Dimension bist. Nach ausführen des Befehls wirst du an den würfelpark teleportiert und deine Dimension zurückgesetzt. Solltest du danach deine Fahrzeuge dennoch nicht sehen können schauen wir woran es sonst liegt

**Comment by BlackBeast79** [comment]
ok mache ich danke schon mal

**Comment by BlackBeast79** [comment]
ok der Fehler ist erledigt war in Falscher dimension dafür kann ich jetzt das auto nicht starten wenn auf Motoren zeichen gehe ist das nicht anwählbar wie im Fehlerbericht https://github.com/Beyond-RP/BeyondRoleplay-Public/issues/4#issue-1088588844

![01 Motor](https://user-images.githubusercontent.com/23469608/147406926-ce752778-3afc-4374-abb9-709dcd500798.JPG)
n

**Comment by BlackBeast79** [comment]
dies bezüglich heist es halt dann warten bis das erledigt ist aber aktuell geht Familie auf alle fälle vor. macht guten support und das sogar während der feiertage
