### ISSUE TITLE
Voice-Entfernung

### ISSUE THREAD

**Issue by CoolioLP** [Beyond-RP/BeyondRoleplay-Public#7]
hallo, seid dem update, ist es nicht mehr möglich die entfernung des ingamevoices einzustellen.

achso und der Farming Hotkey ist auch noch nicht implementiert ;)

**Comment by Asrothear** [comment]
Voice Range ist gefixt.

Was genau meinst du mit dem Farming Hotkey

**Comment by CoolioLP** [comment]
naja dass man beim farmen nicht die ganze zeit e spammen muss, sprich nur einmal e drücken und er farmt

**Comment by Asrothear** [comment]
moved to https://gitlab.beyondroleplay.de/beyondroleplay/BeyondRoleplay-Public/-/issues/7
