### ISSUE TITLE
BUGREPORT-Eisenerz

### ISSUE THREAD

**Issue by CoolioLP** [Beyond-RP/BeyondRoleplay-Public#8]
Man kann beim Eisenerz kein Eisen farmen, habe dort alles abgelaufen, aber es kann nichts gesammelt werden. Es ist nichtmal ein triggerpunkt dort, um zu sehen woran es vllt liegen könnte.

**Comment by BeyondRoleplayDE** [comment]
Das funktioniert schon, du bist offensichtlich nur an der falschen Position

**Comment by CoolioLP** [comment]
nein ich stand genau auf der Position...

**Comment by BeyondRoleplayDE** [comment]
Dann hätte es ja funktioniert, ich vermute das du nicht in der Mine warst und es deswegen bei dir nicht geht.

**Comment by Asrothear** [comment]
Ohne jeglichen Logs lässt sich von nichts anderem ausgehen
